/**
 * Live DOM Target Element Resolver & Geometric Verification
 * Re-resolves proposed targets against the active live DOM.
 * Implements Constitution Article XIV (Action allowlisting & target identity checks).
 */

import { TargetSelector, ResolveTargetElementResponse, SimpleBounds } from "../common/types.js";
import { CREDENTIAL_INPUT_PATTERNS } from "../common/constants.js";
import { resolveElementInShadowRoots } from "./shadow-dom-extractor.js";

/**
 * Checks if a DOM element is visible in the viewport.
 */
export function isElementVisible(el: HTMLElement): boolean {
  if (!el) return false;
  const style = window.getComputedStyle(el);
  if (style.display === "none" || style.visibility === "hidden" || style.opacity === "0") {
    return false;
  }
  // Canvas elements render via GPU compositing — their bounding rect may be zero on first
  // paint or under CSS transforms (e.g. Google Docs editor canvas). Trust the computed
  // style instead of the rect for canvas elements.
  if (el.tagName.toLowerCase() === "canvas") {
    return true;
  }
  // In JSDOM getBoundingClientRect may be 0, so check style attributes
  const rect = el.getBoundingClientRect ? el.getBoundingClientRect() : { width: 0, height: 0 };
  if (rect.width === 0 && rect.height === 0 && el.offsetParent === null && el.tagName !== "BODY" && el.tagName !== "HTML") {
    // If offsetParent is null and element is not detached/body/html, it may be hidden
    if (style.display === "none" || (el.getAttribute("style") || "").includes("display: none")) {
      return false;
    }
  }
  return true;
}

/**
 * Checks if an element is a credential or secret input.
 */
export function isCredentialInput(el: HTMLElement): boolean {
  const tagName = el.tagName.toLowerCase();
  if (tagName !== "input" && tagName !== "textarea") return false;

  const type = (el.getAttribute("type") || "").toLowerCase();
  if (type === "password") return true;

  const autocomplete = (el.getAttribute("autocomplete") || "").toLowerCase();
  const name = (el.getAttribute("name") || "").toLowerCase();
  const id = (el.getAttribute("id") || "").toLowerCase();
  const ariaLabel = (el.getAttribute("aria-label") || "").toLowerCase();
  const placeholder = (el.getAttribute("placeholder") || "").toLowerCase();

  const combined = `${type} ${autocomplete} ${name} ${id} ${ariaLabel} ${placeholder}`;
  return CREDENTIAL_INPUT_PATTERNS.some(pattern => pattern.test(combined));
}

/**
 * Re-resolves target element on the live document and gathers geometric bounds.
 */
export function resolveTargetElement(target?: TargetSelector): ResolveTargetElementResponse {
  if (!target) {
    return {
      found: false,
      isInteractive: false,
      isVisible: false,
      isCredentialField: false,
      error: "No target selector provided"
    };
  }

  let element: HTMLElement | null = null;

  // 1. Try by nodeId — checks real id attr, then data-priv-node-id (generated by dom-extractor),
  //    then any attribute named "id" with that value.
  if (target.nodeId) {
    element =
      document.getElementById(target.nodeId) ||
      (document.querySelector(`[data-priv-node-id="${target.nodeId}"]`) as HTMLElement | null) ||
      (document.querySelector(`[id="${target.nodeId}"]`) as HTMLElement | null);
  }

  // 2. Try CSS Selector
  if (!element && target.cssSelector) {
    try {
      element = document.querySelector(target.cssSelector) as HTMLElement;
    } catch {
      // Invalid selector syntax
    }
  }

  // 3. Try XPath
  if (!element && target.xpath) {
    try {
      const xpathResult = document.evaluate(
        target.xpath,
        document,
        null,
        XPathResult.FIRST_ORDERED_NODE_TYPE,
        null
      );
      element = xpathResult.singleNodeValue as HTMLElement;
    } catch {
      // Invalid xpath
    }
  }

  // 4. Try matching text content if specified — broad search across all interactive/visible elements.
  //    First pass: exact match. Second pass: substring/contains match.
  if (!element && target.expectedText) {
    const needle = target.expectedText.trim().toLowerCase();
    const candidates = Array.from(
      document.querySelectorAll(
        "button, a, input[type='submit'], input[type='button'], [role='button'], [role='link'], [role='menuitem'], label, span, div, li, img, svg, iframe"
      )
    ) as HTMLElement[];

    const getElText = (el: HTMLElement) => {
      return (
        el.textContent ||
        (el as HTMLInputElement).value ||
        el.getAttribute("aria-label") ||
        el.getAttribute("title") ||
        el.getAttribute("alt") ||
        el.querySelector("img")?.getAttribute("alt") ||
        ""
      ).trim().toLowerCase();
    };

    // Exact match first
    element = candidates.find(el => getElText(el) === needle) || null;

    // Substring match fallback (e.g. "Sign in with Google" contains "google")
    if (!element) {
      element = candidates.find(el => {
        const text = getElText(el);
        return text.length > 0 && (text.includes(needle) || needle.includes(text));
      }) || null;
    }
  }

  // 5. Try resolving within open/attached Shadow DOM roots
  if (!element && (target.nodeId || target.cssSelector)) {
    element = resolveElementInShadowRoots(target.nodeId || target.cssSelector!);
  }

  // 6. Try resolving by viewport coordinates (elementFromPoint) if x and y are provided
  if (!element && target.x !== undefined && target.y !== undefined) {
    if (typeof document.elementFromPoint === "function") {
      const hit = document.elementFromPoint(target.x, target.y) as HTMLElement | null;
      if (hit) {
        element = hit;
      }
    }
  }

  if (!element) {
    return {
      found: false,
      isInteractive: false,
      isVisible: false,
      isCredentialField: false,
      error: `Element not found for target: ${JSON.stringify(target)}`
    };
  }

  const rect = element.getBoundingClientRect ? element.getBoundingClientRect() : { x: 0, y: 0, width: 0, height: 0 };
  const currentBounds: SimpleBounds = {
    x: (rect as any).left ?? rect.x ?? 0,
    y: (rect as any).top ?? rect.y ?? 0,
    width: rect.width || 0,
    height: rect.height || 0
  };

  const visible = isElementVisible(element);
  const credential = isCredentialInput(element);
  const tag = element.tagName.toLowerCase();
  // Interactivity: standard form controls, links, canvas-based editors,
  // iframes (e.g. Google Sign-In button), images, contenteditable surfaces, elements with role=button/textbox, and tabbable elements
  const isInteractive = ["a", "button", "input", "select", "textarea", "canvas", "iframe", "img"].includes(tag) ||
    element.hasAttribute("onclick") ||
    element.getAttribute("role") === "button" ||
    element.getAttribute("role") === "textbox" ||
    element.getAttribute("contenteditable") === "true" ||
    element.getAttribute("contenteditable") === "" ||
    (element.hasAttribute("tabindex") && element.getAttribute("tabindex") !== "-1");

  return {
    type: "RESOLVE_TARGET_ELEMENT_RESPONSE",
    found: true,
    isInteractive,
    isVisible: visible,
    isCredentialField: credential,
    currentBounds,
    nodeId: element.id || element.getAttribute("data-priv-node-id") || target.nodeId,
    tagName: tag
  };
}
